### ISSUE TITLE
Don't use scaled images for our "giants"

### ISSUE THREAD

**Issue by boennemann** [excellenteasy/bradypodion.io#1]

**Comment by davidpfahler** [comment]
I don't understand this by just reading the title.

**Comment by boennemann** [comment]
That's because it's more a note for me than anything else, more important for you: #2 

for the record: The "giants" (angular, jquery) are currently displayed with 150px width, but the images are 400px.

We need to create 150px and 150px@2x versions and dynamically swap the image source on retina screens.
